version: "3.7"
services:
  
  app:
    image: tiagotele/python_api
    depends_on:
      - prometheus
    restart: always
    ports:
      - "8080:80"

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
