name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install libs
        run: pip install -r requirements.txt

      - name: Unit Test
        run: |
          make unit_tests
    
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag tiagotele/python_api:$(date +%y-%m-%d_%H-%M)
    
      - name: List Docker images
        run: docker images

